name: Backend Continuous Deployment

on:
  # push:
  #   branches: [main]
  #   paths: 'starter/backend/**'
  workflow_dispatch:

defaults:
  run:
    working-directory: ./starter/backend

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
