name: Backend Continuous Deployment

on:
  # push:
  #   branches: [main]
  #   paths: 'starter/backend/**'
  workflow_dispatch:

defaults:
  run:
    working-directory: ./starter/backend

jobs:

  test:
    runs-on: ubuntu-latest

  build:
    runs-on: ubuntu-latest

  deploy:
    runs-on: ubuntu-latest
